version: '2'

services:

  db:

    image: postgres:alpine
    ports:
      - "8087:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: files

  server-front:

    image: node14front
    build: ./front
    ports:
      - 8081:8080
      
  back-end:

    image: jdk17
    build: ./back
    ports:
      - "8085:8085"